global:
  scrape_interval: 15s # Scrape metrics every 15 seconds

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Scrape Prometheus itself

  - job_name: 'node-app'
    static_configs:
      - targets: ['node-app:8080'] # Scrape Node.js app on port 8080
        labels:
          group: 'node-js'
